### ISSUE TITLE
The code for calculating RMSE, PSNR and SSIM in paper

### ISSUE THREAD

**Issue by lxxcontinue** [xuhangc/shadow#1]
Can I get the code for calculating RMSE, PSNR and SSIM in your paper?

**Comment by xuhangc** [comment]
Hello, you can find our evaluation code in the evaluation folder. However, we now recommend using  [torchmetrics](https://torchmetrics.readthedocs.io/en/latest/), as they use CUDA acceleration and produce nearly identical results.

**Comment by lxxcontinue** [comment]
Thanks for your answer! I have another question，what resolution images are used to calculate the metrics in your paper

**Comment by xuhangc** [comment]
> Thanks for your answer! I have another question，what resolution images are used to calculate the metrics in your paper

The resolution is 512 * 512.
