### ISSUE TITLE
The Kligler dataset shared on the Google cloud drive is incomplete

### ISSUE THREAD

**Issue by lxxcontinue** [xuhangc/shadow#2]
The Kligler dataset shared on the Google drive is incomplete. The target images of train are empty, and part of the mask is missing.

**Comment by xuhangc** [comment]
Sorry for the inconvenience, I have reuploaded the dataset in GDrive. I have also uploaded a backup copy to [Baidu Netdisk](https://pan.baidu.com/s/1QAIab86GlpQQNNqGD7UgYA?pwd=cp7e).
