### ISSUE TITLE
may you update the checkpoints 

### ISSUE THREAD

**Issue by Hammer-888** [xuhangc/shadow#4]
thanks as title

**Comment by xuhangc** [comment]
Sure, when I have the time to undergo retraining, I will upload my weight parameters.

**Comment by xuhangc** [comment]
@Hammer-888 Hello, I have uploaded the weights to [GDrive](https://drive.google.com/drive/folders/1XAOXBkavlKiA08f8YgKRsKvX_1UhyVhm?usp=share_link). The retraining process is not yet complete, so there will be updates soon. As this is a retraining result, its metrics may differ slightly from those reported in our paper, but the difference is marginal.

**Comment by Hammer-888** [comment]
> @Hammer-888 Hello, I have uploaded the weights to [GDrive](https://drive.google.com/drive/folders/1XAOXBkavlKiA08f8YgKRsKvX_1UhyVhm?usp=share_link). The retraining process is not yet complete, so there will be updates soon. As this is a retraining result, its metrics may differ slightly from those reported in our paper, but the difference is marginal.

thanks a lot
