### ISSUE TITLE
Colour shift in output images.

### ISSUE THREAD

**Issue by shubhoppo** [xuhangc/shadow#5]
![00079_](https://user-images.githubusercontent.com/108809090/236791415-e771f2b0-0aac-4138-a21a-1fd6984f4110.png)
![00079](https://user-images.githubusercontent.com/108809090/236791574-c4699b29-8961-4166-8e14-d831016f2b13.png)
After inference on test images, there is a change in colour or texture of output image. Any ways to handle it?

**Comment by xuhangc** [comment]
Yes, this is a limitation in our work, which is due to our MLP module. However, on the whole this is because the dataset size is too small. If you feed more data or attempt more data augmentation, the results would be improved.
