### ISSUE TITLE
About training data.

### ISSUE THREAD

**Issue by ZZZHANG-jx** [xuhangc/shadow#6]
Hello, nice job! Here I have some questions.

Which dataset did you use for training? It doesn't seem to be mentioned in the paper. I noticed that the provided model weights have different weights for different test data. Is this training based on a split from the Jung et al and Kligler et al datasets, or if not, which dataset was used for training, and why do different test sets have their own model weights?

**Comment by xuhangc** [comment]
Thank you for your inquiry. The datasets are individually trained and tested, with the training/testing split available in the netdisk. We have separately trained and tested all models on both Jung and Kligler datasets.
